name: easy_permission_validator
description: PermissonHandler is a package that manages permissions on Android
  and iOS, with this package you can find an easy way to use the
  PermissonHandler library.
version: 3.1.1
homepage: https://github.com/ajviera/easy_permission_validator

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
